---
- name: Create volume for Swag container
  community.docker.docker_volume:
    name: "swag"

- name: Install docker-swag container
  community.docker.docker_container:
    name: swag
    image: lscr.io/linuxserver/swag:latest
    capabilities:
      - NET_ADMIN
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "{{ timezone }}"
      # URL: "{{ domain_url }}"
      # VALIDATION: http
      # SUBDOMAINS: nextcloud,gitea
      # ONLY_SUBDOMAINS: "false"
      # STAGING: "true"
    volumes:
      - swag:/config"
    ports:
      - 443:443
      - 80:80
    restart_policy: unless-stopped
