---
- name: Create a volume for Linkding
  community.general.docker_volume:
    volume_name: 'linkding_data'

- name: Configure Linkding container
  community.docker.docker_container:
    name: linkding
    hostname: linkding
    image: "sissbruecker/linkding:latest"
    pull: true
    volumes:
      - "{{ docker_dir }}/linkding/data:/etc/linkding/data"
    ports:
      - "{{ ext_port }}:9090"
    env:
      LD_SUPERUSER_NAME: "{{ default_user }}"
      LD_SUPERUSER_PASSWORD: "{{ default_pass }}"
    restart_policy: unless-stopped
