---
- name: Run all tasks
  hosts: futro
  become: false
  vars_files:
    - group_vars/main.yml

  roles:
    - role: homer
      become: true
      tags:
        - homer
        - containers
      when: enable_homer | default(False)

    - role: containers/frontends/nitter
      become: true
      tags:
        - nitter
        - containers

    - role: containers/services/linkding
      become: true
      tags:
        - linkding
        - containers

  handlers:
    - name: Import handlers
      ansible.builtin.import_tasks: handlers/main.yml
