---
- name: Run all roles
  hosts: futro
  become: true
  vars_files:
    - group_vars/main.yml
  roles:
    - role: system
      tags: system

    - role: hifis.unattended_upgrades
      when: ansible_facts['os_family'] == 'Debian'

    - role: docker
      tags: docker

    - role: homer
      tags:
        - homer
        - containers
      when: enable_homer | default(False)

    - role: containers/frontends/nitter
      tags:
        - nitter
        - frontends
        - containers

    - role: containers/frontends/libreddit
      tags:
        - libreddit
        - frontends
        - containers

    - role: containers/frontends/invidious
      tags:
        - invidious
        - frontends
        - containers

    - role: containers/frontends/chatbot
      tags:
        - chatbot
        - frontends
        - containers

    - role: containers/services/linkding
      tags:
        - linkding
        - services
        - containers

    - role: containers/services/wireguard
      tags:
        - wireguard
        - services
        - containers

    - role: containers/services/syncthing
      tags:
        - syncthing
        - services
        - containers

    - role: containers/system/portainer
      tags:
        - portainer
        - containers

    - role: nginx
      tags:
        - nginx
