---
- name: Install dependency
  ansible.builtin.apt:
    name: "{{ pkg }}"
    state: present
    update_cache: true
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python3-pip
  loop_control:
    loop_var: pkg

- name: Add GPG key for Docker
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/debian bullseye stable
    state: present

- name: Install docker
  ansible.builtin.apt:
    name: "{{ line_item }}"
    state: present
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  loop_control:
    loop_var: line_item

- name: Ensure group docker exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ sudo_user }}"
    groups:
      - docker
    append: true

- name: Install Python docker dependency
  ansible.builtin.pip:
    name: docker
    state: present

- name: Make sure that the docker folders exists
  ansible.builtin.file:
    path: "{{ docker_dir }}"
    owner: "{{ sudo_user }}"
    group: "{{ sudo_user }}"
    mode: '0755'
    state: directory

- name: Ensure Docker is active
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
