---
- name: Create volume for Wireguard
  community.docker.docker_volume:
    volume_name: wireguard_volume

- name: Configure Wireguard containerd
  community.docker.docker_container:
    image: lscr.io/linuxserver/wireguard:latest
    name: wireguard
    capabilities:
      - NET_ADMIN
      - SYS_MODULE
    env:
      - PUID: "1000"
      - PGID: "1000"
      - TZ: "Europe/London"
      - SERVERPORT: "{{ wireguard_port }}"
      - PEERS: 1
      - PEERDNS: auto
      - INTERNAL_SUBNET: "10.13.13.0"
      - ALLOWEDIPS: "0.0.0.0/0"
      - LOG_CONFS: true
    volumes:
      - wireguard_volume:/config
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
    sysctls:
      - "net.ipv4.conf.all.src_valid_mark=1"
    restart_policy: unless-stopped
