---
docker_deps:
  - 'apt-transport-https'
  - 'ca-certificates'
  - 'curl'
  - 'gnupg-agent'
  - 'software-properties-common'
  - 'python3-pip'
  - 'python3-docker'
  - 'docker-compose'

docker_packages:
  - 'docker-ce'
  - 'docker-ce-cli'
  - 'containerd.io'
  - 'docker-compose'
