---
- name: Allow SSH
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: Allow Nginx Proxy manager
  community.general.ufw:
    rule: allow
    port: '81'
    comment: 'Nginx Proxy Manager'

- name: Allow Nginx HTTP
  community.general.ufw:
    rule: allow
    port: '80'
    comment: 'Nginx HTTP'

- name: Allow Syncthing web
  community.general.ufw:
    rule: allow
    port: '8384'
    comment: 'Syncthing web'

- name: Allow Syncthing sync
  community.general.ufw:
    rule: allow
    port: '22000'
    proto: tcp
    comment: 'Syncthing sync'

- name: Allow Syncthing QUIC
  community.general.ufw:
    rule: allow
    port: '22000'
    proto: udp
    comment: 'Syncthing QUIC'

- name: Allow Syncthing discovery
  community.general.ufw:
    rule: allow
    port: '21027'
    proto: udp
    comment: 'Syncthing discovery'

- name: Allow Cockpit
  community.general.ufw:
    rule: allow
    port: '9090'
    proto: tcp
    comment: 'Cockpit'

- name: Deny all incoming traffic
  community.general.ufw:
    direction: incoming
    policy: deny

- name: Enable UFW
  community.general.ufw:
    state: enabled
