---
- name: Make sure the Homer container is created and running
  community.docker.docker_container:
    name: homer
    image: "b4bz/homer:latest"
    pull: true
    state: started
    env:
      UID: "{{ guid }}"
      GID: "{{ guid }}"
      INIT_ASSETS: "1"
      TZ: "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/www/assets"
    ports:
      - 8080:8080
    restart_policy: always

- name: Make sure cors-container is created and running
  community.docker.docker_container:
    name: 'cors-container'
    image: "imjacobclark/cors-container"
    pull: true
    state: 'started'
    ports:
      - 3000:3000
    restart_policy: unless-stopped

# - name: Add {{ container_name }} to the SWAG network (reverse-proxy)
#   community.docker.docker_network:
#     name: swag_internal_network
#     connected:
#       - homer
#       - cors-container
#     appends: true
#   when: enable_swag
