---
- name: Install pip
  ansible.builtin.package:
    name: python3-pip
    state: present

# see https://stackoverflow.com/questions/75608323/how-do-i-solve-error-externally-managed-environment-every-time-i-use-pip-3
- name: fix externally-managed-environment
  ansible.builtin.file:
    path: /usr/lib/python3.11/EXTERNALLY-MANAGED
    state: absent

- name: Install the Xresources parser
  ansible.builtin.pip:
    name: git+https://github.com/alex27riva/xparser.git

- name: Install the Xresources file
  ansible.builtin.copy:
    dest: "/home/{{ username }}/.Xresources"
    src: "files/colorschemes/{{ colorscheme | lower }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Parse the Xresources file
  ansible.builtin.shell:
    cmd: "python3 -c 'import xrp; import json; result = xrp.parse_file(\"/home/{{ username }}/.Xresources\", encoding=\"utf8\"); print(json.dumps(dict(result.resources), indent = 4).replace(\"*.\", \"\").replace(\"*\", \"\"))'"
  register: xresources
  changed_when: false

- name: Save variables
  ansible.builtin.set_fact:
    colors: "{{ xresources.stdout | from_json }}"
