---
- name: Install pip
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Install the Xresources parser
  ansible.builtin.pip:
    name: xparser

- name: Install the Xresources file
  ansible.builtin.copy:
    dest: "/home/{{ username }}/.Xresources"
    src: "files/colorschemes/{{ colorscheme | lower }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Parse the Xresources file
  ansible.builtin.shell:
    cmd: "python3 -c 'import xrp; import json; result = xrp.parse_file(\"/home/{{ username }}/.Xresources\", encoding=\"utf8\"); print(json.dumps(dict(result.resources), indent = 4).replace(\"*.\", \"\").replace(\"*\", \"\"))'"
  register: xresources
  changed_when: false

- name: Save variables
  ansible.builtin.set_fact:
    colors: "{{ xresources.stdout | from_json }}"
