---
- name: Configure Wireguard container
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: 'ngoduykhanh/wireguard-ui:latest'
    pull: true
    capabilities:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.ip_forward: '1'
      net.ipv4.conf.all.src_valid_mark: '1'
    ports:
      - "{{ wg_server_port }}:{{ wg_server_port }}/udp"
      - "{{ ext_port }}:5000/tcp"
    env:
      WGUI_USERNAME: "{{ wgui_username }}"
      WGUI_PASSWORD: "{{ wgui_password }}"
      WGUI_ENDPOINT_ADDRESS: "{{ ddns_endpoint }}"
      WGUI_SERVER_LISTEN_PORT: "{{ wg_server_port }}"
      WGUI_SERVER_POST_UP_SCRIPT: "{{ post_up }}"
      WGUI_SERVER_POST_DOWN_SCRIPT: "{{ post_down }}"
      WGUI_DNS: "{{ pihole_ip }}"
      WGUI_MANAGE_START: 'true'
      WGUI_MANAGE_RESTART: 'true'
    volumes:
      - "{{ docker_dir }}/wireguard/db:/app/db"
      - "{{ docker_dir }}/wireguard/config:/etc/wireguard"
    restart_policy: unless-stopped
    privileged: true
