---
- name: Configure Wireguard container
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: 'ngoduykhanh/wireguard-ui:latest'
    capabilities:
      - NET_ADMIN
    volumes:
      - "{{ docker_dir }}/wireguard/db:/app/db"
      - "/etc/wireguard:/etc/wireguard"
    env:
      WGUI_USERNAME: "{{ wgui_username }}"
      WGUI_PASSWORD: "{{ wgui_password }}"
      WGUI_SERVER_LISTEN_PORT: "{{ wireguard_port }}"
      WGUI_MANAGE_START: 'true'
      WGUI_MANAGE_RESTART: 'true'
    network_mode: host
    restart_policy: unless-stopped
