---
- name: Create a volume for Portainer
  community.general.docker_volume:
    volume_name: 'portainer_data'

- name: Deploy Portainer container
  community.docker.docker_container:
    name: portainer
    hostname: portainer
    image: 'portainer/portainer-ce:latest'
    pull: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'portainer_data:/data'
    networks:
      - name: internal
    restart_policy: unless-stopped
