---
- name: Create volume for Postgres
  community.docker.docker_volume:
    volume_name: postgresdata

- name: Create volume for inv Companion
  community.docker.docker_volume:
    volume_name: companioncache

- name: Create network for Invidious
  community.docker.docker_network:
    name: invidious_network

- name: Create repo directory
  ansible.builtin.file:
    path: "{{ invidious_repo_dir }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'
    state: directory

# Currently the repository has to be cloned, this is because the init-invidious-db.sh file and the config/sql directory have to be mounted to the postgres container.
- name: Clone Invidious repo
  ansible.builtin.git: # noqa: latest
    repo: 'https://github.com/iv-org/invidious.git'
    dest: "{{ invidious_repo_dir }}"
    version: master

- name: Create postgres container
  community.docker.docker_container:
    name: 'invidious-db'
    hostname: 'invidious-db'
    image: 'docker.io/library/postgres:14'
    restart_policy: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - "{{ invidious_repo_dir }}/config/sql:/config/sql"
      - "{{ invidious_repo_dir }}/docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh"
    env:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    networks:
      - name: invidious_network
      - name: internal

# - name: Create inv_sig_helper container
#   community.docker.docker_container:
#     name: 'inv_sig_helper'
#     hostname: 'inv_sig_helper'
#     image: 'quay.io/invidious/inv-sig-helper:latest'
#     init: true
#     command: ["--tcp", "0.0.0.0:12999"]
#     env:
#       RUST_LOG: info
#     restart_policy: unless-stopped
#     cap_drop:
#       - ALL
#     read_only: true
#     security_opts:
#       - no-new-privileges:true
#     networks:
#       - name: invidious_network

- name: Create invidious_companion container
  community.docker.docker_container:
    name: 'companion'
    hostname: 'companion'
    image: 'quay.io/invidious/invidious-companion:latest'
    pull: true
    env:
      SERVER_SECRET_KEY: "{{ invidious_companion_key }}"
      RUST_LOG: info
    restart_policy: unless-stopped
    cap_drop:
      - ALL
    read_only: true
    security_opts:
      - no-new-privileges:true
    networks:
      - name: invidious_network
    volumes:
      - companioncache:/var/tmp/youtubei.js:rw

- name: Configure Invidious container
  community.docker.docker_container:
    name: 'invidious'
    hostname: 'invidious'
    image: 'quay.io/invidious/invidious:master'
    pull: true
    env:
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: invidious-db
          port: 5432
        check_tables: true
        invidious_companion:
        - private_url: "http://companion:8282/companion"
        hmac_key: "{{ invidious_hmac_key }}"
        invidious_companion_key: "{{ invidious_companion_key }}"
    healthcheck:
      test: 'wget -nv --tries=1 --spider http://localhost:3000/api/v1/trending || exit 1'
      interval: 30s
      timeout: 5s
      retries: 2
    networks:
      - name: invidious_network
      - name: internal
    restart_policy: unless-stopped
    recreate: true
