---
- name: Configure Chatbot container
  community.docker.docker_container:
    name: chatbot-ui
    hostname: chatbot-ui
    image: 'ghcr.io/mckaywrigley/chatbot-ui:main'
    pull: true
    env:
      OPENAI_API_KEY: "{{ openai_api_key }}"
    networks:
      - name: internal
    restart_policy: unless-stopped
